[package]
name = "bindings_generator"
version = "0.1.0"
authors = ["Joshua Groves <josh@joshgroves.com>"]

[dependencies]
bindgen = "0.64.0"
convert_case = "0.6.0"
regex = "1.7.1"

[[bin]]
name = "bindings_generator"
path = "src/main.rs"
